# Generated by Django 6.0.3 on 2026-04-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(default='Savings', max_length=20),
            preserve_default=False,
        ),
    ]
