# Generated by Django 6.0.3 on 2026-05-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ifsc_code',
            field=models.CharField(default='AUREON0001', max_length=20),
            preserve_default=False,
        ),
    ]
