# Generated by Django 6.0.3 on 2026-06-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_account_ifsc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
