# Generated by Django 6.0.3 on 2026-06-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
